### ISSUE TITLE
3.3.0 is breaking the migration of ghost 

### ISSUE THREAD

**Issue by MaluNoPeleke** [TryGhost/knex-migrator#145]
As explained over in the forum the update of knex-migrator to 3.3.0 seems to break the migration for self-hosted ghost instances: https://forum.ghost.org/t/problem-with-knex-migrator/7655?u=peleke
At the moment the npm package should be removed until the issue is fixed.

**Comment by gargol** [comment]
After a little bit of digging have found that `getKnexMigrator` method was removed with these changes - https://github.com/TryGhost/knex-migrator/commit/8835b2cd69a126880529989ce928778615e5adb7. Will revert it and release a patch :+1: Thanks for the report @MaluNoPeleke!

**Comment by MaluNoPeleke** [comment]
Good to know, happy to test again as soon as it is solved and available via npm.

**Comment by MaluNoPeleke** [comment]
Hi @gargol, I just updated Ghost from 2.23.3 -> 2.23.4 with knex-migrator 3.3.1 and now it shows a different error:

```
ERROR Cannot find module '../migrations'

Cannot find module '../migrations'

Error Code: 
    MODULE_NOT_FOUND

----------------------------------------

Error: Cannot find module '../migrations'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/peleke7/lib/node_modules/knex-migrator/lib/index.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /home/peleke7/lib/node_modules/knex-migrator/lib/utils.js:162:20
    at tryCatcher (/home/peleke7/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/peleke7/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/peleke7/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:574:18)
```

It seems that it is still not solved. Should I open a new ticket or do you want to re-open this one?
