### ISSUE TITLE
OuterError: Field length of `customer_id` in `members_stripe_customers` is too long!

### ISSUE THREAD

**Issue by naymapl** [TryGhost/knex-migrator#236]
Hi. I try to update ghost and have strage issue - its never happend before.

knex-migrator migrate or node index give me this error:

```
[2020-10-27 13:20:53] ERROR Cannot remove permission(Delete snippets) from role(Editor) - permission does not exist

Cannot remove permission(Delete snippets) from role(Editor) - permission does not exist

"OuterError: Field length of `customer_id` in `members_stripe_customers` is too long!"

Error ID:
    400

----------------------------------------

RollbackError: Cannot remove permission(Delete snippets) from role(Editor) - permission does not exist
    at RollbackError.KnexMigrateError (/home/naymaeu/websites/nayblopl/node_modules/knex-migrator/lib/errors.js:7:26)
    at new RollbackError (/home/naymaeu/websites/nayblopl/node_modules/knex-migrator/lib/errors.js:31:26)
    at /home/naymaeu/websites/nayblopl/node_modules/knex-migrator/lib/index.js:440:23
    at tryCatcher (/home/naymaeu/websites/nayblopl/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/naymaeu/websites/nayblopl/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/naymaeu/websites/nayblopl/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/naymaeu/websites/nayblopl/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/naymaeu/websites/nayblopl/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/naymaeu/websites/nayblopl/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/naymaeu/websites/nayblopl/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/naymaeu/websites/nayblopl/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/naymaeu/websites/nayblopl/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

Error: Cannot remove permission(Delete snippets) from role(Editor) - permission does not exist
    at down (/home/naymaeu/websites/nayblopl/core/server/data/migrations/utils.js:151:23)
    at async Object.down (/home/naymaeu/websites/nayblopl/core/server/data/migrations/utils.js:239:13)
    at async Object.down (/home/naymaeu/websites/nayblopl/core/server/data/migrations/utils.js:263:17)
    at async Object.down (/home/naymaeu/websites/nayblopl/core/server/data/migrations/utils.js:263:17)
```

Anybody can help me with thise. Thank you so much for help.

**Comment by matthanley** [comment]
Hey 👋 We ask that you please do not use GitHub for help or support 😄. We use GitHub solely for bug-tracking and on-going feature development.

Many questions can be answered by reviewing our documentation. If you can't find an answer then our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
