### ISSUE TITLE
Duplicate migrations can happen and then the health check fails

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/knex-migrator#76]
This bug is a bit of a double-whammy.

1. It seems that under some conditions migrations can end up being duplicated. 
2. Once a duplicate migration happens, the knex-migrator health check fails saying that "migrations are missing".

-----

Not sure why the duplicate is happening, don't have an exact reproduction case, but I have an example case:

In Ghost, on Ghost(Pro), during the migration to 1.13, some blogs (we've found 5 so far) are ending up with duplicate migrations for theme permissions, such that the migration table looks like:

```
*************************** 7. row ***************************
            id: 7
          name: 1-add-permissions-redirect.js
       version: 1.9
currentVersion: 1.9
*************************** 8. row ***************************
            id: 8
          name: 1-custom-template-post.js
       version: 1.13
currentVersion: 1.14
*************************** 9. row ***************************
            id: 9
          name: 2-theme-permissions.js
       version: 1.13
currentVersion: 1.14
*************************** 10. row ***************************
            id: 10
          name: 2-theme-permissions.js
       version: 1.13
currentVersion: 1.14
```

After this happens, Ghost refuses to start:

```
NAME: DatabaseIsNotOkError
CODE: DB_NEEDS_MIGRATION
MESSAGE: Migrations are missing. Please run knex-migrator migrate.

level:normal

If knex-migrator is not installed, please run "npm install -g knex-migrator" 
Read more here: https://github.com/TryGhost/knex-migrator
DatabaseIsNotOkError: Migrations are missing. Please run knex-migrator migrate.
    at DatabaseIsNotOkError.KnexMigrateError (/home/ghost/node_modules/knex-migrator/lib/errors.js:7:26)
    at new DatabaseIsNotOkError (/home/ghost/node_modules/knex-migrator/lib/errors.js:19:26)
    at /home/ghost/node_modules/knex-migrator/lib/index.js:648:23
    at /home/ghost/node_modules/lodash/lodash.js:4944:15
...
```

**Comment by ErisDS** [comment]
Going to close this in favour of #78 which has a clear reproduction case.
#77 also solved the error being incorrect.
