### ISSUE TITLE
gql.json.replaceStatements is not a function

### ISSUE THREAD

**Issue by tespio** [TryGhost/knex-migrator#84]
To whom it may concern

Usually updating ghost manually here, until now had no issue. However, after downloading Ghost-1.16.0.zip, unpacking it over the existing install and running knex-migrator i get this when i run:
**NODE_ENV=production DEBUG=knex-migrator:* knex-migrator migrate*
```
  knex-migrator:utils [ '1.13', '1.3', '1.4', '1.5', '1.7', '1.9' ] +0ms
  knex-migrator:utils [ '1-create-tables.js', '2-create-fixtures.js' ] +17ms
  knex-migrator:index Version init expected: 2 +1ms
  knex-migrator:index Version init actual: 2 +0ms
  knex-migrator:utils [ '1-custom-template-post.js', '2-theme-permissions.js' ] +2ms
  knex-migrator:index Version 1.13 expected: 2 +0ms
  knex-migrator:index Version 1.13 actual: 1 +0ms
  knex-migrator:index Version 1.3 expected: 1 +0ms
  knex-migrator:index Version 1.3 actual: 1 +1ms
  knex-migrator:index Version 1.4 expected: 1 +0ms
  knex-migrator:index Version 1.4 actual: 1 +0ms
  knex-migrator:index Version 1.5 expected: 1 +0ms
  knex-migrator:index Version 1.5 actual: 1 +0ms
  knex-migrator:index Version 1.7 expected: 1 +0ms
  knex-migrator:index Version 1.7 actual: 1 +0ms
  knex-migrator:utils [ '1-add-permissions-redirect.js' ] +0ms
  knex-migrator:index Version 1.9 expected: 1 +0ms
  knex-migrator:index Version 1.9 actual: 1 +0ms
  knex-migrator:index Need to execute migrations for: 1.13 +0ms
  knex-migrator:index Before hook +0ms
[2017-10-31 13:22:36] INFO Creating database backup
[2017-10-31 13:22:36] INFO Database backup written to: /var/www/ghost/ghost/content/data/init-3-ninja.ghost.2017-10-31.json
  knex-migrator:utils [ '1-custom-template-post.js', '2-theme-permissions.js' ] +147ms
  knex-migrator:index Migrate: 1.13 with 2 tasks. +0ms
  knex-migrator:index Tasks: [{"name":"1-custom-template-post.js"},{"name":"2-theme-permissions.js"}] +0ms
  knex-migrator:index Skipping:1-custom-template-post.js +3ms
  knex-migrator:index Running:2-theme-permissions.js +2ms
[2017-10-31 13:22:36] WARN (0/6) Adding permissions fixtures for themes
  knex-migrator:index Rolling back: gql.json.replaceStatements is not a function +14ms
  knex-migrator:index Destroy connection +1ms
  knex-migrator:index Destroyed connection +2ms
[2017-10-31 13:22:36] ERROR

NAME: MigrationScript
MESSAGE: gql.json.replaceStatements is not a function

level:normal

Error occurred while executing the following migration: 2-theme-permissions.js
MigrationScript: gql.json.replaceStatements is not a function
    at MigrationScript.KnexMigrateError (/var/www/ghost/ghost/node_modules/knex-migrator/lib/errors.js:7:26)
    at new MigrationScript (/var/www/ghost/ghost/node_modules/knex-migrator/lib/errors.js:26:26)
    at /var/www/ghost/ghost/node_modules/knex-migrator/lib/index.js:353:19
    at tryCatcher (/var/www/ghost/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/ghost/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/ghost/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/ghost/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/ghost/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/www/ghost/ghost/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/ghost/ghost/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

TypeError: gql.json.replaceStatements is not a function
    at preProcessFilters (/var/www/ghost/ghost/core/server/models/plugins/filter.js:87:49)
    at applyDefaultAndCustomFilters (/var/www/ghost/ghost/core/server/models/plugins/filter.js:174:22)
    at Function.findAll (/var/www/ghost/ghost/core/server/models/base/index.js:465:24)
    at fetchRelationData (/var/www/ghost/ghost/core/server/data/schema/fixtures/utils.js:83:47)
    at Object.addFixturesForRelation (/var/www/ghost/ghost/core/server/data/schema/fixtures/utils.js:137:12)
    at /var/www/ghost/ghost/core/server/data/migrations/versions/1.13/2-theme-permissions.js:33:22
    at tryCatcher (/var/www/ghost/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/ghost/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/ghost/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/ghost/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/ghost/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/www/ghost/ghost/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/ghost/ghost/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
```

**Comment by kirrg001** [comment]
Hey @tespio!

Looks like your dependencies didn't install correctly. `replaceStatements` was added in GQL 0.0.8, [see](https://github.com/TryGhost/GQL/commit/9d18055fcfaba844b93ee16d4efa41fa6c34fc9c). And Ghost uses 0.0.8. 

Maybe you forgot to run `yarn` to install/update your dependency tree.
Closing, because this shouldn't be a bug.

Let me know if you were able to resolve your problem by running `yarn`.
