### ISSUE TITLE
Got "Tarn: opt.max must be an integer > 0" when running knex-migrator init

### ISSUE THREAD

**Issue by go-on-blog** [TryGhost/knex-migrator#99]
$ heroku run "knex-migrator init"
    Running knex-migrator init on ⬢ my-app... up, run.6370 (Free)
    [2018-03-31 07:47:54] ERROR

    MESSAGE: Tarn: opt.max must be an integer > 0

    Error: Tarn: opt.max must be an integer > 0
        at new Pool (/app/node_modules/tarn/lib/Pool.js:29:13)
        at Client_MySQL.initializePool (/app/node_modules/knex/lib/client.js:306:17)
        at Client_MySQL.Client (/app/node_modules/knex/lib/client.js:117:12)
        at new Client_MySQL (/app/node_modules/knex/lib/dialects/mysql/index.js:62:20)
        at Knex (/app/node_modules/knex/lib/index.js:60:34)
        at Object.connect (/app/node_modules/knex-migrator/lib/database.js:25:12)
        at KnexMigrator.init (/app/node_modules/knex-migrator/lib/index.js:83:32)
        at /app/node_modules/knex-migrator/bin/knex-migrator-init:24:29
        at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
        at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)
        at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:582:21)
        at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)

when using ghost@1.21.6 and a ClearDB database installed this way:

    $ heroku addons:create cleardb:ignite
    $ heroku config:set \
    database__connection__user=... \
    database__connection__password=... \
    database__connection__host=... \
    database__connection__database=...

    $ heroku config:set database__pool__max=2

Any idea of what is wrong?

**Comment by kirrg001** [comment]
This does not look like a bug.

From `tarn`:

>   if (typeof opt.max !== 'number' || opt.max <= 0 || opt.max !== Math.round(opt.max)) {

I think it's passed as String from heroku:

> $ heroku config:set database__pool__max=2

If someone needs to support string and transformation to integer, it would be either mysql or knex, but not knex-migrator.
